version: "3.9"
services:
  triton-server:
    container_name: triton-server
    image: nvcr.io/nvidia/tritonserver:23.02-py3
    command:
      [
         "tritonserver",
        "--model-repository=/code/triton-model-repository",
      ]
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - /home/amar/dev/work/projects/dojo/model_repository:/code/triton-model-repository
    deploy:
      resources:
        reservations:
          devices:
          - driver: "nvidia"
            device_ids: ["0"]
            capabilities: [gpu]
    restart: always
