train_dataset_dir: data/raw-preprocessed/train
val_ratio: 0.05
test_dataset_dir: data/raw-preprocessed/test
predict_dataset_dir: null
train_transform: conf/transform/default.yaml
cache: False
image_size: 224
batch_size: 64
s3_folder: s3://ai-data-log/dojo-testing
