project_type: classification
task: preprocess
resume: False
resume_epoch: null
resume_ckpt_fpath: null

defaults:
  - dataset: default
  - model: default
  - trainer: default
  - preprocess: default
  - callbacks: default

logger:
  project: ???
  id: null
  resume: ${resume}
  job_type: ${task}
