project_type: classification
task: preprocess
resume: False
resume_epoch: null
resume_ckpt_fpath: null

preprocess:
  longest_max_size: null
  smallest_max_size: 224
  dataset_dir: data/raw
  output_dir: ${preprocess.dataset_dir}-preprocessed

trainer:
  precision: 16-mixed
  max_epochs: 5

model:
  num_classes: 10
  lr: 3e-8

dataset:
  train_dataset_dir: data/raw-preprocessed/train
  val_ratio: 0.05
  test_dataset_dir: data/raw-preprocessed/test
  predict_dataset_dir: null
  batch_size: 16
  train_transform: conf/transform/default.yaml

logger:
  project: ???
  id: null
  resume: ${resume}
  job_type: ${task}

callbacks:
  checkpoints:
    monitor_metric: val/acc
    save_best: True
    save_latest: True
    save_every_n_epochs: 0
  other_callbacks:
    - classification-generate_test_report:
        max_num_images_per_label_pred: 10
    - classification-validate_architecture
    - classification-log_artifacts_callback
