project_type: classification
task: export
resume: True
resume_epoch: best
resume_ckpt_fpath: null

defaults:
  - dataset: default
  - model: default
  - trainer: default
  - preprocess: default
  - callbacks: default

logger:
  project: common-classification-jivi_assessment
  id: 4ev5scga
  resume: ${resume}
  job_type: ${task}
