project_type: classification
task: preprocess
resume: False
resume_epoch: best
resume_ckpt_fpath: null

preprocess:
  longest_max_size: null
  smallest_max_size: 224
  dataset_dir: /home/ubuntu/members/amar/projects/auto-classification-window_reflection/data/raw
  output_dir: ${preprocess.dataset_dir}-preprocessed
trainer:
  precision: 16-mixed
  max_epochs: 100
model:
  num_classes: 3
  lr: 3e-8
dataset:
  train_dataset_dir: /home/ubuntu/members/amar/dojo/test/cifar10-images/train2
  val_ratio: 0.05
  test_dataset_dir: null
  predict_dataset_dir: null
  batch_size: 16
  log_dataset: True
  train_transform: conf/transform/default.yaml
logger:
  project: auto-classification-window_reflection
  id: null
  resume: ${resume}
  job_type: ${task}
callbacks:
  checkpoints:
    monitor_metric: val/acc
    save_best: True
    save_latest: True
    save_every_n_epochs: 0
  other_callbacks:
    - classification-generate_test_report:
        max_num_images_per_label_pred: 10
    - classification-validate_architecture
    - classification-log_artifacts_callback
