project_type: classification
task: train
resume_ckpt_fpath: null
trainer:
  precision: 16-mixed
  max_epochs: 1
model:
  num_classes: 10
dataset:
  train_dataset_dir: /home/ubuntu/members/amar/dojo/test/cifar10-images/train2
  log_dataset: True
logger:
  project: common-classification-test-dojo-v2
  id: null
  resume: ${resume}
callbacks:
  checkpoints:
    monitor_metric: val/acc
    save_best: True
    save_latest: True
    save_every_n_epochs: 0
