__version__: 1.4.0
transform:
  __class_fullname__: Compose
  additional_targets: {}
  bbox_params: null
  is_check_shapes: true
  keypoint_params: null
  p: 1.0
  transforms:
  - __class_fullname__: Compose
    additional_targets: {}
    bbox_params: null
    is_check_shapes: true
    keypoint_params: null
    p: 1.0
    transforms:
    - __class_fullname__: LongestMaxSize
      always_apply: false
      interpolation: 1
      max_size: 256
      p: 1
    - __class_fullname__: RandomResizedCrop
      always_apply: false
      height: 224
      interpolation: 1
      p: 1.0
      ratio:
      - 0.75
      - 1.3333333333333333
      scale:
      - 0.8
      - 1.0
      width: 224
    - __class_fullname__: ToFloat
      always_apply: false
      max_value: null
      p: 1.0
    - __class_fullname__: Blur
      always_apply: false
      blur_limit:
      - 3
      - 3
      p: 0.5
    - __class_fullname__: RandomBrightnessContrast
      always_apply: false
      brightness_by_max: true
      brightness_limit:
      - -0.2
      - 0.2
      contrast_limit:
      - -0.2
      - 0.2
      p: 0.5
    - __class_fullname__: Defocus
      alias_blur:
      - 0.1
      - 0.3
      always_apply: false
      p: 0.5
      radius:
      - 3
      - 5
    - __class_fullname__: ImageCompression
      always_apply: false
      compression_type: 0
      p: 0.5
      quality_lower: 60
      quality_upper: 100
    - __class_fullname__: ToGray
      always_apply: false
      p: 0.1
    - __class_fullname__: HorizontalFlip
      always_apply: false
      p: 0.5
  - __class_fullname__: ToTensorV2
    always_apply: true
    p: 1.0
    transpose_mask: false
